sudo: false
language: ruby
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
branches:
  only:
    - master
cache:
  bundler: true
  directories:
    - vendor/bundle
    - $HOME/.rvm
before_install:
install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
  - travis_retry bundle
  - jekyll build
after_success:
notifications:
  email: false
